// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: FSMessage.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Protocol1 *int32 `protobuf:"varint,1,req,name=protocol1" json:"protocol1,omitempty"`
	Protocol2 *int32 `protobuf:"varint,2,opt,name=protocol2" json:"protocol2,omitempty"`
}

func (x *Head) Reset() {
	*x = Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FSMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_FSMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_FSMessage_proto_rawDescGZIP(), []int{0}
}

func (x *Head) GetProtocol1() int32 {
	if x != nil && x.Protocol1 != nil {
		return *x.Protocol1
	}
	return 0
}

func (x *Head) GetProtocol2() int32 {
	if x != nil && x.Protocol2 != nil {
		return *x.Protocol2
	}
	return 0
}

type FSMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *Head   `protobuf:"bytes,1,req,name=head" json:"head,omitempty"`
	Cmd  *string `protobuf:"bytes,2,req,name=cmd" json:"cmd,omitempty"`
	Body []byte  `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
}

func (x *FSMessage) Reset() {
	*x = FSMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FSMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSMessage) ProtoMessage() {}

func (x *FSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_FSMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSMessage.ProtoReflect.Descriptor instead.
func (*FSMessage) Descriptor() ([]byte, []int) {
	return file_FSMessage_proto_rawDescGZIP(), []int{1}
}

func (x *FSMessage) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *FSMessage) GetCmd() string {
	if x != nil && x.Cmd != nil {
		return *x.Cmd
	}
	return ""
}

func (x *FSMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_FSMessage_proto protoreflect.FileDescriptor

var file_FSMessage_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x46, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x42, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x31, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x31, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x32, 0x22, 0x5c, 0x0a, 0x09, 0x46, 0x53, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x42, 0x1d, 0x5a, 0x1b, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x67, 0x6f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65,
}

var (
	file_FSMessage_proto_rawDescOnce sync.Once
	file_FSMessage_proto_rawDescData = file_FSMessage_proto_rawDesc
)

func file_FSMessage_proto_rawDescGZIP() []byte {
	file_FSMessage_proto_rawDescOnce.Do(func() {
		file_FSMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_FSMessage_proto_rawDescData)
	})
	return file_FSMessage_proto_rawDescData
}

var file_FSMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_FSMessage_proto_goTypes = []any{
	(*Head)(nil),      // 0: network.message.Head
	(*FSMessage)(nil), // 1: network.message.FSMessage
}
var file_FSMessage_proto_depIdxs = []int32{
	0, // 0: network.message.FSMessage.head:type_name -> network.message.Head
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_FSMessage_proto_init() }
func file_FSMessage_proto_init() {
	if File_FSMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FSMessage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FSMessage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FSMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FSMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FSMessage_proto_goTypes,
		DependencyIndexes: file_FSMessage_proto_depIdxs,
		MessageInfos:      file_FSMessage_proto_msgTypes,
	}.Build()
	File_FSMessage_proto = out.File
	file_FSMessage_proto_rawDesc = nil
	file_FSMessage_proto_goTypes = nil
	file_FSMessage_proto_depIdxs = nil
}
