// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: ginproxy.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单条待注册路由：url_path 可含 ":name" 段；method 为空表示通配所有方法。
type GinRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlPath       string                 `protobuf:"bytes,1,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinRoute) Reset() {
	*x = GinRoute{}
	mi := &file_ginproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinRoute) ProtoMessage() {}

func (x *GinRoute) ProtoReflect() protoreflect.Message {
	mi := &file_ginproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinRoute.ProtoReflect.Descriptor instead.
func (*GinRoute) Descriptor() ([]byte, []int) {
	return file_ginproxy_proto_rawDescGZIP(), []int{0}
}

func (x *GinRoute) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

func (x *GinRoute) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// 客户端 -> 服务端：连接建立后上报本地可代理的路由清单。
type GinRouteRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*GinRoute            `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinRouteRegistration) Reset() {
	*x = GinRouteRegistration{}
	mi := &file_ginproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinRouteRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinRouteRegistration) ProtoMessage() {}

func (x *GinRouteRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_ginproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinRouteRegistration.ProtoReflect.Descriptor instead.
func (*GinRouteRegistration) Descriptor() ([]byte, []int) {
	return file_ginproxy_proto_rawDescGZIP(), []int{1}
}

func (x *GinRouteRegistration) GetRoutes() []*GinRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

// 服务端 -> 客户端：注册确认。
type GinRegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinRegisterAck) Reset() {
	*x = GinRegisterAck{}
	mi := &file_ginproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinRegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinRegisterAck) ProtoMessage() {}

func (x *GinRegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_ginproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinRegisterAck.ProtoReflect.Descriptor instead.
func (*GinRegisterAck) Descriptor() ([]byte, []int) {
	return file_ginproxy_proto_rawDescGZIP(), []int{2}
}

func (x *GinRegisterAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GinRegisterAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 路径参数捕获（":name" 段回填）。
type GinParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinParam) Reset() {
	*x = GinParam{}
	mi := &file_ginproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinParam) ProtoMessage() {}

func (x *GinParam) ProtoReflect() protoreflect.Message {
	mi := &file_ginproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinParam.ProtoReflect.Descriptor instead.
func (*GinParam) Descriptor() ([]byte, []int) {
	return file_ginproxy_proto_rawDescGZIP(), []int{3}
}

func (x *GinParam) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GinParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// HTTP 头（多值）。
type GinHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinHeader) Reset() {
	*x = GinHeader{}
	mi := &file_ginproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinHeader) ProtoMessage() {}

func (x *GinHeader) ProtoReflect() protoreflect.Message {
	mi := &file_ginproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinHeader.ProtoReflect.Descriptor instead.
func (*GinHeader) Descriptor() ([]byte, []int) {
	return file_ginproxy_proto_rawDescGZIP(), []int{4}
}

func (x *GinHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GinHeader) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// 服务端 -> 客户端：把命中的 HTTP 请求转发给远端处理。
// matched_pattern 为服务端命中的注册模板（含 ":name" 原样），
// params 为服务端已捕获的路径参数——客户端据此直接回调、无需二次匹配。
type GinHTTPRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Method         string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	UrlPath        string                 `protobuf:"bytes,2,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	RawQuery       string                 `protobuf:"bytes,3,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	MatchedPattern string                 `protobuf:"bytes,4,opt,name=matched_pattern,json=matchedPattern,proto3" json:"matched_pattern,omitempty"`
	Params         []*GinParam            `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	Headers        []*GinHeader           `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	Body           []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GinHTTPRequest) Reset() {
	*x = GinHTTPRequest{}
	mi := &file_ginproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinHTTPRequest) ProtoMessage() {}

func (x *GinHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ginproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinHTTPRequest.ProtoReflect.Descriptor instead.
func (*GinHTTPRequest) Descriptor() ([]byte, []int) {
	return file_ginproxy_proto_rawDescGZIP(), []int{5}
}

func (x *GinHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GinHTTPRequest) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

func (x *GinHTTPRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *GinHTTPRequest) GetMatchedPattern() string {
	if x != nil {
		return x.MatchedPattern
	}
	return ""
}

func (x *GinHTTPRequest) GetParams() []*GinParam {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GinHTTPRequest) GetHeaders() []*GinHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GinHTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 客户端 -> 服务端：回传 HTTP 响应，服务端再写回网页端。
type GinHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*GinHeader           `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GinHTTPResponse) Reset() {
	*x = GinHTTPResponse{}
	mi := &file_ginproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GinHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GinHTTPResponse) ProtoMessage() {}

func (x *GinHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ginproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GinHTTPResponse.ProtoReflect.Descriptor instead.
func (*GinHTTPResponse) Descriptor() ([]byte, []int) {
	return file_ginproxy_proto_rawDescGZIP(), []int{6}
}

func (x *GinHTTPResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GinHTTPResponse) GetHeaders() []*GinHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GinHTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_ginproxy_proto protoreflect.FileDescriptor

const file_ginproxy_proto_rawDesc = "" +
	"\n" +
	"\x0eginproxy.proto\x12\x0fnetwork.message\"=\n" +
	"\bGinRoute\x12\x19\n" +
	"\burl_path\x18\x01 \x01(\tR\aurlPath\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"I\n" +
	"\x14GinRouteRegistration\x121\n" +
	"\x06routes\x18\x01 \x03(\v2\x19.network.message.GinRouteR\x06routes\"2\n" +
	"\x0eGinRegisterAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"2\n" +
	"\bGinParam\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"5\n" +
	"\tGinHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\x86\x02\n" +
	"\x0eGinHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x19\n" +
	"\burl_path\x18\x02 \x01(\tR\aurlPath\x12\x1b\n" +
	"\traw_query\x18\x03 \x01(\tR\brawQuery\x12'\n" +
	"\x0fmatched_pattern\x18\x04 \x01(\tR\x0ematchedPattern\x121\n" +
	"\x06params\x18\x05 \x03(\v2\x19.network.message.GinParamR\x06params\x124\n" +
	"\aheaders\x18\x06 \x03(\v2\x1a.network.message.GinHeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\"s\n" +
	"\x0fGinHTTPResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x124\n" +
	"\aheaders\x18\x02 \x03(\v2\x1a.network.message.GinHeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04bodyB\x1dZ\x1btouchgocore/network/messageb\x06proto3"

var (
	file_ginproxy_proto_rawDescOnce sync.Once
	file_ginproxy_proto_rawDescData []byte
)

func file_ginproxy_proto_rawDescGZIP() []byte {
	file_ginproxy_proto_rawDescOnce.Do(func() {
		file_ginproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ginproxy_proto_rawDesc), len(file_ginproxy_proto_rawDesc)))
	})
	return file_ginproxy_proto_rawDescData
}

var file_ginproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ginproxy_proto_goTypes = []any{
	(*GinRoute)(nil),             // 0: network.message.GinRoute
	(*GinRouteRegistration)(nil), // 1: network.message.GinRouteRegistration
	(*GinRegisterAck)(nil),       // 2: network.message.GinRegisterAck
	(*GinParam)(nil),             // 3: network.message.GinParam
	(*GinHeader)(nil),            // 4: network.message.GinHeader
	(*GinHTTPRequest)(nil),       // 5: network.message.GinHTTPRequest
	(*GinHTTPResponse)(nil),      // 6: network.message.GinHTTPResponse
}
var file_ginproxy_proto_depIdxs = []int32{
	0, // 0: network.message.GinRouteRegistration.routes:type_name -> network.message.GinRoute
	3, // 1: network.message.GinHTTPRequest.params:type_name -> network.message.GinParam
	4, // 2: network.message.GinHTTPRequest.headers:type_name -> network.message.GinHeader
	4, // 3: network.message.GinHTTPResponse.headers:type_name -> network.message.GinHeader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ginproxy_proto_init() }
func file_ginproxy_proto_init() {
	if File_ginproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ginproxy_proto_rawDesc), len(file_ginproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ginproxy_proto_goTypes,
		DependencyIndexes: file_ginproxy_proto_depIdxs,
		MessageInfos:      file_ginproxy_proto_msgTypes,
	}.Build()
	File_ginproxy_proto = out.File
	file_ginproxy_proto_goTypes = nil
	file_ginproxy_proto_depIdxs = nil
}
