// Code generated by protoc-gen-go.
// source: Message.proto
// DO NOT EDIT!

/*
Package network_message is a generated protocol buffer package.

It is generated from these files:
	Message.proto

It has these top-level messages:
	Head
	FSMessage
*/
package network_message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Head struct {
	Protocol1        *int32 `protobuf:"varint,1,req,name=protocol1" json:"protocol1,omitempty"`
	Protocol2        *int32 `protobuf:"varint,2,opt,name=protocol2" json:"protocol2,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Head) Reset()                    { *m = Head{} }
func (m *Head) String() string            { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()               {}
func (*Head) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Head) GetProtocol1() int32 {
	if m != nil && m.Protocol1 != nil {
		return *m.Protocol1
	}
	return 0
}

func (m *Head) GetProtocol2() int32 {
	if m != nil && m.Protocol2 != nil {
		return *m.Protocol2
	}
	return 0
}

type FSMessage struct {
	Head             *Head  `protobuf:"bytes,1,req,name=Head" json:"Head,omitempty"`
	Body             []byte `protobuf:"bytes,2,req,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FSMessage) Reset()                    { *m = FSMessage{} }
func (m *FSMessage) String() string            { return proto.CompactTextString(m) }
func (*FSMessage) ProtoMessage()               {}
func (*FSMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FSMessage) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *FSMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Head)(nil), "network.message.Head")
	proto.RegisterType((*FSMessage)(nil), "network.message.FSMessage")
}

func init() { proto.RegisterFile("Message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xf5, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcf, 0x4b, 0x2d, 0x29, 0xcf,
	0x2f, 0xca, 0xd6, 0xcb, 0x85, 0x08, 0x2b, 0xe9, 0x70, 0xb1, 0x78, 0xa4, 0x26, 0xa6, 0x08, 0x09,
	0x72, 0x71, 0x82, 0x55, 0x24, 0xe7, 0xe7, 0x18, 0x4a, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x22, 0x0b,
	0x19, 0x49, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x2a, 0xd9, 0x71, 0x71, 0xba, 0x05, 0x43, 0x4d, 0x14,
	0x52, 0x86, 0x68, 0x05, 0xab, 0xe6, 0x36, 0x12, 0xd5, 0x43, 0x33, 0x5a, 0x0f, 0x6c, 0x2e, 0x0f,
	0x17, 0x4b, 0x52, 0x7e, 0x4a, 0xa5, 0x04, 0x93, 0x02, 0x93, 0x06, 0x0f, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x63, 0x90, 0xfc, 0x34, 0x8e, 0x00, 0x00, 0x00,
}
