// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: rpc.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grpc_Msg_FullMethodName = "/network.message.Grpc/Msg"
)

// GrpcClient is the client API for Grpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcClient interface {
	Msg(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FSMessage, FSMessage], error)
}

type grpcClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcClient(cc grpc.ClientConnInterface) GrpcClient {
	return &grpcClient{cc}
}

func (c *grpcClient) Msg(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FSMessage, FSMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Grpc_ServiceDesc.Streams[0], Grpc_Msg_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FSMessage, FSMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_MsgClient = grpc.BidiStreamingClient[FSMessage, FSMessage]

// GrpcServer is the server API for Grpc service.
// All implementations must embed UnimplementedGrpcServer
// for forward compatibility.
type GrpcServer interface {
	Msg(grpc.BidiStreamingServer[FSMessage, FSMessage]) error
	mustEmbedUnimplementedGrpcServer()
}

// UnimplementedGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrpcServer struct{}

func (UnimplementedGrpcServer) Msg(grpc.BidiStreamingServer[FSMessage, FSMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Msg not implemented")
}
func (UnimplementedGrpcServer) mustEmbedUnimplementedGrpcServer() {}
func (UnimplementedGrpcServer) testEmbeddedByValue()              {}

// UnsafeGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcServer will
// result in compilation errors.
type UnsafeGrpcServer interface {
	mustEmbedUnimplementedGrpcServer()
}

func RegisterGrpcServer(s grpc.ServiceRegistrar, srv GrpcServer) {
	// If the following call pancis, it indicates UnimplementedGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grpc_ServiceDesc, srv)
}

func _Grpc_Msg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcServer).Msg(&grpc.GenericServerStream[FSMessage, FSMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Grpc_MsgServer = grpc.BidiStreamingServer[FSMessage, FSMessage]

// Grpc_ServiceDesc is the grpc.ServiceDesc for Grpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.message.Grpc",
	HandlerType: (*GrpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Msg",
			Handler:       _Grpc_Msg_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
