package util

const (
	MILLISECONDS_OF_DAY       int64 = 24 * MILLISECONDS_OF_HOUR
	MILLISECONDS_OF_HOUR      int64 = 60 * MILLISECONDS_OF_MINUTE
	MILLISECONDS_OF_10_MINUTE int64 = 10 * MILLISECONDS_OF_MINUTE
	MILLISECONDS_OF_MINUTE    int64 = 60 * MILLISECONDS_OF_SECOND
	MILLISECONDS_OF_SECOND    int64 = 1000
)

var DEBUG bool
var Fps int
var Version string
